### ISSUE TITLE
mainnet doesn't work for predicate scanning

### ISSUE THREAD

**Issue by aulneau** [hirosystems/chainhook#207]
when running `chainhook predicates scan ./path/to/predicate.json --mainnet`

it errors with `Network unknown`

We need this functionality to continue work on the new stacking focused API being built.

**Comment by lgalabru** [comment]
Hey @aulneau! could you share the predicate you're using? Thanks, just want to make sure it correctly includes a mainnet node in the networks map.

**Comment by aulneau** [comment]
Oop, thank you! such a silly mistake on my part. i've made a new issue for better error message :) https://github.com/hirosystems/chainhook/issues/209
