### ISSUE TITLE
Add unit tests for predicates documented in README

### ISSUE THREAD

**Issue by aulneau** [hirosystems/chainhook#210]
When trying to get all contract deployments using the `*` value, no hits are found. Testing other predicates, eg the arkidiko predicate, works as expected.

Here is the predicate:
```json
{
  "chain": "stacks",
  "uuid": "1",
  "name": "Contract deploys",
  "version": 1,
  "networks": {
    "mainnet": {
      "if_this": {
        "scope": "contract_deployment",
        "deployer": "*"
      },
      "then_that": {
        "http_post": {
          "url": "http://127.0.0.1:8787/api/v1/chainhooks",
          "authorization_header": "Bearer cn389ncoiwuencr"
        }
      },
      "start_block": 0
    }
  }
}
```

**Comment by lgalabru** [comment]
Quickly patched in https://github.com/hirosystems/chainhook/pull/214.

**Comment by smcclellan** [comment]
Thank you for filing! We will track this work here: https://github.com/hirosystems/chainhook/issues/287
I'll close this in favor of that one.
