### ISSUE TITLE
Chainhook template generation silently fails

### ISSUE THREAD

**Issue by sabbyanandan** [hirosystems/chainhook#219]
The following commands don't generate the templates as documented. No errors, but no files either. 

>╭─sabbyanandan ~/hiro/chainhook ‹ruby-2.7.6› ‹develop●›
╰─$ chainhook predicates new --stacks sabbysooz

> ╭─sabbyanandan ~/hiro/chainhook ‹ruby-2.7.6› ‹develop●›
╰─$ chainhook predicates new --bitcoin fooz

As well, the new config generation as an option is missing:

```
╭─sabbyanandan ~/hiro/chainhook ‹ruby-2.7.6› ‹develop●›
╰─$ chainhook config new --testnet
error: Found argument 'config' which wasn't expected, or isn't valid in this context

USAGE:
    chainhook <SUBCOMMAND>

For more information try --help
```

**Comment by aulneau** [comment]
Duplicate https://github.com/hirosystems/chainhook/issues/208

**Comment by sabbyanandan** [comment]
Ah missed it; closing.
