### ISSUE TITLE
Error running chainhook node

### ISSUE THREAD

**Issue by utibeabasi6** [hirosystems/chainhook#244]
Hey, i get the following error when running chainhook
![image](https://user-images.githubusercontent.com/66149718/234642838-37169903-4fb0-40b0-8396-b354c891a18e.png)

**Comment by utibeabasi6** [comment]
@lgalabru

**Comment by lgalabru** [comment]
This could come from a bad `bitcoin.conf`. Could you please share your config (credentials stripped out)?

**Comment by utibeabasi6** [comment]
hey
i was using a public rpc endpoint
i started running bitcoind locally and now i get the following
![image](https://user-images.githubusercontent.com/66149718/234669254-c8f5e57d-41d2-4b9e-9a86-08aa11692e25.png)

Heres my config
![image](https://user-images.githubusercontent.com/66149718/234669375-229a11bb-265e-4c11-87dd-dda78153528d.png)

![image](https://user-images.githubusercontent.com/66149718/234669534-d0f04ca5-14ce-47fa-bb98-b3659bb0881e.png)

I just ran the bitcoind node with the default settings

**Comment by utibeabasi6** [comment]
sorry im kinda new to this and im not sure if the blockchain rpc url is correct
i also dont have a stacks node running as well
