### ISSUE TITLE
Downloading blocks takes too long

### ISSUE THREAD

**Issue by utibeabasi6** [hirosystems/chainhook#247]
hey @lgalabru i finally got it to work but its taking quite a while to download the blocks, is this normal?
<img width="621" alt="Screenshot 2023-04-27 at 4 17 14 PM" src="https://user-images.githubusercontent.com/66149718/234908184-e6b03611-9274-44d1-912a-f7d856273c0b.png">

**Comment by utibeabasi6** [comment]
there are about 2425388 and its just at 5K after about an hour

**Comment by lgalabru** [comment]
These logs are indicating that you're using an outdated version.

**Comment by utibeabasi6** [comment]
hmm
i followed the instructions on the README tho

**Comment by utibeabasi6** [comment]
can you guide me to how i can set this up with the latest version?

**Comment by utibeabasi6** [comment]
@lgalabru ?

**Comment by utibeabasi6** [comment]
<img width="424" alt="Screenshot 2023-04-27 at 5 35 29 PM" src="https://user-images.githubusercontent.com/66149718/234930738-a0b38884-8e97-4f96-a69a-2cca2d7fad91.png">

This is my version btw

**Comment by lgalabru** [comment]
```
$ git pull
$ cargo chainhook-install
```

**Comment by utibeabasi6** [comment]
<img width="422" alt="Screenshot 2023-04-27 at 5 48 35 PM" src="https://user-images.githubusercontent.com/66149718/234933645-2959ae63-0a84-4f18-a7b6-017d599a1db6.png">

I cloned the latest version today

**Comment by utibeabasi6** [comment]
<img width="1004" alt="Screenshot 2023-04-29 at 11 39 28 PM" src="https://user-images.githubusercontent.com/66149718/235326978-5e3dca2e-8d05-4ae5-9271-0f39a7f67b40.png">

hey @lgalabru any idea why i'm getting this error?

**Comment by lgalabru** [comment]
Note on speed / eventual future feature: this layer was designed to run on a cloud infrastructure, so we are assuming that `bitcoind` and `chainhook` will be running in different pods / containers.
That being said, we could have a `developer` mode, where we could read and ingest the bitcoin chainstate by reading it from disk - https://github.com/ordilabs/bitcoin-scanner for reference.

**Comment by lgalabru** [comment]
Theses traces are not very useful @utibeabasi6, could you copy paste the text (full line) instead of partial screenshots?
Thanks.

**Comment by utibeabasi6** [comment]
@lgalabru 
`thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', components/chainhook-event-observer/src/hord/db/mod.rs:233:21`

**Comment by lgalabru** [comment]
@utibeabasi6 could you share your bitcoin configuration file (strip the credentials)? can you confirm that you're running version >= 24 ?

**Comment by utibeabasi6** [comment]
hey @lgalabru 
my bitcoin.conf file just contains `zmqpubhashblock=tcp://0.0.0.0:18543`
but i think the bitcoind version is 22.0
<img width="415" alt="Screenshot 2023-05-05 at 6 38 48 AM" src="https://user-images.githubusercontent.com/66149718/236384490-bc3d0df2-13d9-4582-a9db-fbee973de0f8.png">

**Comment by utibeabasi6** [comment]
but thats the latest version from the bitcoin-core site

**Comment by utibeabasi6** [comment]
heres an error i encountered when i ran the `predicates scan` command

`May 05 08:57:31.883 ERRO unable to retrieve #2431869 (attempt #1): unable to parse response (RPC error response: RpcError { code: -8, message: "Block height out of range", data: None })`

**Comment by lgalabru** [comment]
Will close, in favor of https://github.com/hirosystems/chainhook/issues/233.
@utibeabasi6 you'll need to install bitcoin v24 for interacting with ordinals.
