### ISSUE TITLE
ERRO Unable to augment bitcoin block

### ISSUE THREAD

**Issue by yarsawyer** [hirosystems/chainhook#249]
$chainhook service start --predicate-path=./predicate.json --start-http-api --config-path=./Chainhook.toml
Apr 28 05:35:47.629 INFO Starting service...
Apr 28 05:35:47.629 INFO Ordinal indexing is enabled by default hord, checking index... (use --no-hord to disable ordinals)
Apr 28 05:35:47.639 INFO Resuming hord indexing from block #774938
Apr 28 05:35:47.639 INFO Syncing hord_db: 12377 blocks to download (774938: 787314), using 8 network threads
Apr 28 05:35:48.183 INFO Queueing compacted block #774945
Apr 28 05:35:48.561 INFO Queueing compacted block #774940
Apr 28 05:35:48.872 INFO Queueing compacted block #774939
Apr 28 05:35:49.205 INFO Queueing compacted block #774943
Apr 28 05:35:49.623 INFO Queueing compacted block #774941
Apr 28 05:35:50.020 INFO Queueing compacted block #774942
Apr 28 05:35:50.344 INFO Queueing compacted block #774944
Apr 28 05:35:50.639 INFO Queueing compacted block #774938
Apr 28 05:35:50.639 INFO Dequeuing block #774938 for processing (# blocks inboxed: 7)
Apr 28 05:35:50.725 INFO Computing ordinal number for Satoshi point 0x93a622fb1b8579291f7e3569d95dbb618de20a6ce2494b949ff9408642342943:0:0 (block #774938)
Apr 28 05:35:50.725 INFO Computing ordinal number for Satoshi point 0x68f2a04ac37b994d59aaa0b590153d492933913b3d60b5901bc23248545d2c3a:0:0 (block #774938)
Apr 28 05:35:50.725 INFO Computing ordinal number for Satoshi point 0xc08724d8d864f27551771c2885e85cdfbf6c7ac922514ed5495f7cff02d0f2e9:0:0 (block #774938)
Apr 28 05:35:50.726 INFO Computing ordinal number for Satoshi point 0xecdeb0a72c2bb77f36908f72b63d27e032811440ea4bcea8d936727bd9bf743c:0:0 (block #774938)
Apr 28 05:35:50.726 INFO Computing ordinal number for Satoshi point 0xc5afde7345f89cf541b1ee51bf8c93d3ea28c0841680f3fdf8c254d95b64ab04:0:0 (block #774938)
Apr 28 05:35:50.727 INFO Computing ordinal number for Satoshi point 0x078be4a73a490d0adb8a173142c32eba552defc6bedd344cfe14aa51481a8013:0:0 (block #774938)
Apr 28 05:35:50.727 INFO Computing ordinal number for Satoshi point 0x12e749dbd1af412f508ada404656a4bb84422ac8d3afa10ae1716f40f4eae79b:0:0 (block #774938)
Apr 28 05:35:50.727 INFO Computing ordinal number for Satoshi point 0x6c0000402818c2308fdad8fec3d229775b3adb3f77b1427397cdf4f6505bab96:0:0 (block #774938)
Apr 28 05:35:50.727 INFO Computing ordinal number for Satoshi point 0x1e9b44e2495c96045beb881d1b75d3459f52b2371efdd3d11fc46513f807098c:0:0 (block #774938)
Apr 28 05:35:50.727 INFO Computing ordinal number for Satoshi point 0xa67c14aa8e8437262aee06d55bc63d8e2001e3027ad1bccd7ca1a5d19c01b935:0:0 (block #774938)
Apr 28 05:35:50.934 INFO Computing ordinal number for Satoshi point 0x0dd65cb9dfa10d672c16e3741d73eead9085a710ff5f8796ef626799c85f944b:0:0 (block #774938)
Apr 28 05:35:50.934 INFO Computing ordinal number for Satoshi point 0xd258fc0295a6a98bcff37f8eef6d771b65f3a69e2be2cc1c34902c0da973b5c0:0:0 (block #774938)
Apr 28 05:35:50.945 INFO Computing ordinal number for Satoshi point 0xd7a14db2c85c9cece840d44cb11b4f57d5597a7dc09b8d9b357f48762e29c84f:0:0 (block #774938)
Apr 28 05:35:50.948 INFO Computing ordinal number for Satoshi point 0x686390089336addcec25b597a5573f0ec6be39579bede35be9f92c25ad06f6f7:0:0 (block #774938)
Apr 28 05:35:50.951 INFO Computing ordinal number for Satoshi point 0x970cc5dc3c09f323d6a4e0cab52bb254898b036e4a72197278bb30391fb01270:0:0 (block #774938)
Apr 28 05:35:50.952 INFO Computing ordinal number for Satoshi point 0x010c250cadaff06f86505a4324cb1ef3c027470ad3a9fdedec25a427457f946b:0:0 (block #774938)
Apr 28 05:35:51.044 INFO Computing ordinal number for Satoshi point 0x1a94768b175a05eb09201c3b8435c4e6a8691b769848600d408a72712aff318d:0:0 (block #774938)
Apr 28 05:35:51.080 INFO Computing ordinal number for Satoshi point 0x9c8c2e3b184b69b0ec4162cb7d438d63337a39792bba7d59d335f988471306fa:0:0 (block #774938)
Apr 28 05:35:51.082 INFO Computing ordinal number for Satoshi point 0xee21b5240619eab16b498afbcefb673285d5e39f3a597b4a6a54a34dec274a3a:0:0 (block #774938)
Apr 28 05:35:51.146 INFO Computing ordinal number for Satoshi point 0x7bf325e512965080d2fa94c9c1206b2d2925fefb14c5ffc70e04e2d0d12cc04d:0:0 (block #774938)
Apr 28 05:35:51.214 INFO Computing ordinal number for Satoshi point 0x4fc272fa0496c3e084c2ef65adfa5870507bf5fb1172dec2e4e2063d2a6bcf03:0:0 (block #774938)
Apr 28 05:35:51.437 INFO Computing ordinal number for Satoshi point 0x969734270483f95aab4ed2988a96afa11cadeaa372404b42cc32ebffb68c67d7:0:0 (block #774938)
Apr 28 05:35:51.524 INFO Computing ordinal number for Satoshi point 0x53f06b0bf1aa83d51b9d08e85fa952efd5792d79e81ee2d08003c550c3773121:0:0 (block #774938)
Apr 28 05:35:51.921 INFO Computing ordinal number for Satoshi point 0xa19af1b3646f6f5fe164b63db1fd34cf2c14267216620ddbe14572f0dbb513ca:0:0 (block #774938)
Apr 28 05:35:52.084 INFO Computing ordinal number for Satoshi point 0x12c49bbfdbd555f5232bb7aa344f998ef8840019fe4c72e4017a38bf5dcaac4e:0:0 (block #774938)
Apr 28 05:35:54.604 INFO Computing ordinal number for Satoshi point 0x29eee78e1de8a6c10aa85aa79e2ab47ab0481964f7856ab39425811656d4a757:0:0 (block #774938)
Apr 28 05:35:54.938 INFO Computing ordinal number for Satoshi point 0xad274a98ac993c65c20ed23f25b9854362d98659b063e6e086de82c27f5576de:0:0 (block #774938)
Apr 28 05:35:55.139 INFO Computing ordinal number for Satoshi point 0xcbd911c0d1fbf264b1a380ad6efdf9161a6eb130064e59714f462f368698f4cd:0:0 (block #774938)
Apr 28 05:35:56.240 INFO Computing ordinal number for Satoshi point 0x6812087e29167fe96141e73d4cb24e75246b379e3dfa546d191fd786695a42db:0:0 (block #774938)
Apr 28 05:36:12.646 ERRO Unable to augment bitcoin block 774938 with hord_db: block #728057 not in database
block #728057 not in database

when I restart it fails at the same block, but different satoshi point and a message that some other block is not in the database

**Comment by lgalabru** [comment]
hey @yarsawyer! I'll look into this issue, meanwhile, are you running the latest version of the `develop` branch?

**Comment by yarsawyer** [comment]
> hey @yarsawyer! I'll look into this issue, meanwhile, are you running the latest version of the `develop` branch?

yes, the latest version.

I tried to 

chainhook hord db drop 720000 774938 --config-path=./Chainhook.toml

and then

chainhook hord db sync --config-path=./Chainhook.toml 1


but it didn't help

it is stuck on block 774938

I get messages like this:

Apr 28 14:29:03.329 INFO Resuming hord indexing from block #774938
Apr 28 14:29:03.329 INFO Syncing hord_db: 12428 blocks to download (774938: 787365), using 1 network threads
Apr 28 14:29:03.652 INFO Queueing compacted block #774938
Apr 28 14:29:03.652 INFO Dequeuing block #774938 for processing (# blocks inboxed: 0)
Apr 28 14:29:03.734 INFO Computing ordinal number for Satoshi point 0xad274a98ac993c65c20ed23f25b9854362d98659b063e6e086de82c27f5576de:0:0 (block #774938)
Apr 28 14:29:03.734 INFO Computing ordinal number for Satoshi point 0xa19af1b3646f6f5fe164b63db1fd34cf2c14267216620ddbe14572f0dbb513ca:0:0 (block #774938)
Apr 28 14:29:03.734 INFO Computing ordinal number for Satoshi point 0x93a622fb1b8579291f7e3569d95dbb618de20a6ce2494b949ff9408642342943:0:0 (block #774938)
Apr 28 14:29:03.734 INFO Computing ordinal number for Satoshi point 0x1a94768b175a05eb09201c3b8435c4e6a8691b769848600d408a72712aff318d:0:0 (block #774938)
Apr 28 14:29:03.734 INFO Computing ordinal number for Satoshi point 0x6c0000402818c2308fdad8fec3d229775b3adb3f77b1427397cdf4f6505bab96:0:0 (block #774938)
Apr 28 14:29:03.735 INFO Computing ordinal number for Satoshi point 0x686390089336addcec25b597a5573f0ec6be39579bede35be9f92c25ad06f6f7:0:0 (block #774938)
Apr 28 14:29:03.735 INFO Computing ordinal number for Satoshi point 0xa67c14aa8e8437262aee06d55bc63d8e2001e3027ad1bccd7ca1a5d19c01b935:0:0 (block #774938)
Apr 28 14:29:03.735 INFO Computing ordinal number for Satoshi point 0x0dd65cb9dfa10d672c16e3741d73eead9085a710ff5f8796ef626799c85f944b:0:0 (block #774938)
Apr 28 14:29:03.735 INFO Computing ordinal number for Satoshi point 0x9c8c2e3b184b69b0ec4162cb7d438d63337a39792bba7d59d335f988471306fa:0:0 (block #774938)
Apr 28 14:29:03.736 INFO Computing ordinal number for Satoshi point 0x29eee78e1de8a6c10aa85aa79e2ab47ab0481964f7856ab39425811656d4a757:0:0 (block #774938)
Apr 28 14:29:03.840 INFO Computing ordinal number for Satoshi point 0xd7a14db2c85c9cece840d44cb11b4f57d5597a7dc09b8d9b357f48762e29c84f:0:0 (block #774938)
Apr 28 14:29:03.924 INFO Computing ordinal number for Satoshi point 0x1e9b44e2495c96045beb881d1b75d3459f52b2371efdd3d11fc46513f807098c:0:0 (block #774938)
Apr 28 14:29:03.925 INFO Computing ordinal number for Satoshi point 0xd258fc0295a6a98bcff37f8eef6d771b65f3a69e2be2cc1c34902c0da973b5c0:0:0 (block #774938)
Apr 28 14:29:03.953 INFO Computing ordinal number for Satoshi point 0x68f2a04ac37b994d59aaa0b590153d492933913b3d60b5901bc23248545d2c3a:0:0 (block #774938)
Apr 28 14:29:04.176 INFO Computing ordinal number for Satoshi point 0x7bf325e512965080d2fa94c9c1206b2d2925fefb14c5ffc70e04e2d0d12cc04d:0:0 (block #774938)
Apr 28 14:29:04.271 INFO Computing ordinal number for Satoshi point 0x078be4a73a490d0adb8a173142c32eba552defc6bedd344cfe14aa51481a8013:0:0 (block #774938)
Apr 28 14:29:04.360 INFO Computing ordinal number for Satoshi point 0x970cc5dc3c09f323d6a4e0cab52bb254898b036e4a72197278bb30391fb01270:0:0 (block #774938)
Apr 28 14:29:04.530 INFO Computing ordinal number for Satoshi point 0xcbd911c0d1fbf264b1a380ad6efdf9161a6eb130064e59714f462f368698f4cd:0:0 (block #774938)
Apr 28 14:29:04.734 INFO Computing ordinal number for Satoshi point 0x6812087e29167fe96141e73d4cb24e75246b379e3dfa546d191fd786695a42db:0:0 (block #774938)
Apr 28 14:29:04.874 INFO Computing ordinal number for Satoshi point 0x010c250cadaff06f86505a4324cb1ef3c027470ad3a9fdedec25a427457f946b:0:0 (block #774938)
Apr 28 14:29:04.908 INFO Computing ordinal number for Satoshi point 0x969734270483f95aab4ed2988a96afa11cadeaa372404b42cc32ebffb68c67d7:0:0 (block #774938)
Apr 28 14:29:05.075 INFO Computing ordinal number for Satoshi point 0x12e749dbd1af412f508ada404656a4bb84422ac8d3afa10ae1716f40f4eae79b:0:0 (block #774938)
Apr 28 14:29:05.248 INFO Computing ordinal number for Satoshi point 0x12c49bbfdbd555f5232bb7aa344f998ef8840019fe4c72e4017a38bf5dcaac4e:0:0 (block #774938)
Apr 28 14:29:05.339 INFO Computing ordinal number for Satoshi point 0x53f06b0bf1aa83d51b9d08e85fa952efd5792d79e81ee2d08003c550c3773121:0:0 (block #774938)
Apr 28 14:29:08.814 INFO Computing ordinal number for Satoshi point 0x4fc272fa0496c3e084c2ef65adfa5870507bf5fb1172dec2e4e2063d2a6bcf03:0:0 (block #774938)
Apr 28 14:29:10.631 INFO Computing ordinal number for Satoshi point 0xecdeb0a72c2bb77f36908f72b63d27e032811440ea4bcea8d936727bd9bf743c:0:0 (block #774938)
Apr 28 14:29:10.837 INFO Computing ordinal number for Satoshi point 0xc08724d8d864f27551771c2885e85cdfbf6c7ac922514ed5495f7cff02d0f2e9:0:0 (block #774938)
Apr 28 14:29:11.040 INFO Computing ordinal number for Satoshi point 0xc5afde7345f89cf541b1ee51bf8c93d3ea28c0841680f3fdf8c254d95b64ab04:0:0 (block #774938)
Apr 28 14:29:11.737 INFO Computing ordinal number for Satoshi point 0xee21b5240619eab16b498afbcefb673285d5e39f3a597b4a6a54a34dec274a3a:0:0 (block #774938)
Apr 28 14:29:25.440 ERRO Unable to augment bitcoin block 774938 with hord_db: block #724725 not in database
block #724725 not in database

the block that is not found depends on the las processed sat point

**Comment by lgalabru** [comment]
what do you see with 
```
chainhook hord db check --config-path=./Chainhook.toml
```
?

**Comment by yarsawyer** [comment]
chainhook hord db check --config-path=./Chainhook.toml
Missing block 107784
Missing block 107785
Missing block 107786
Missing block 774940
Missing block 774941
Missing block 774943
...
and up to 780000

**Comment by yarsawyer** [comment]
I solved the problem by setting traversal_data_pool to ThreadPool::new(4) instead of 10 in 

update_hord_db_and_augment_bitcoin_block function

this is not an ideal solution as obviously there is a problem with rocksdb but it works now.

**Comment by lgalabru** [comment]
Interesting. Have you seen some errors logs from rocksdb (too many files open, etc)?

**Comment by hugocaillard** [comment]
Might be fixed. Feel free to re-open if not
