### ISSUE TITLE
Recommended number of network threads

### ISSUE THREAD

**Issue by utibeabasi6** [hirosystems/chainhook#255]
hey @lgalabru thanks for the help on the other issue. Upgrading to bitcoin core v24 seems to work
I had a quick question. Whats the recommended number of network threads for the `chainhook hord db sync` command. by default it looks to be 8 but i was wondering if setting it higher can cause any issues

**Comment by smcclellan** [comment]
Task is to document & update default number of network threads.

**Comment by lgalabru** [comment]
The latest config file gives you the ability to set [networking threads, processing threads + memory limit](https://github.com/hirosystems/chainhook/blob/develop/tests/Chainhook.toml).
From there, it's pretty much a Goldilocks process, you'll need to fine tune and settle on what's adequate, based on the hardware resources at your disposal.
Feel free to re-open this issue if you have some other questions.
