### ISSUE TITLE
Create HTTP status page

### ISSUE THREAD

**Issue by CharlieC3** [hirosystems/chainhook#256]
In order to generate availability metrics, it would be useful to have a status page we can periodically hit. The status page should return a HTTP 200 if the service is live and serving traffic.

**Comment by smcclellan** [comment]
There may already be a status endpoint (`/ping`); @lgalabru to specify & ensure it's returning 200s & possibly add more info.

**Comment by CharlieC3** [comment]
Nice, that page seems to work!
