### ISSUE TITLE
Chainhook breaks when streaming zmq from bitcoind if bitcoind streams txs in addition to blocks

### ISSUE THREAD

**Issue by a-straus** [hirosystems/chainhook#257]
Steps to reproduce:

start chainhook with the following configuration:
```
...
[network]
bitcoind_zmq_url = "tcp://0.0.0.0:30001"
...
// rest of config
```

Start a bitcoin node with `bitcoind -zmqpubhashblock=tcp://0.0.0.0:30001 -zmqpubhashtx=tcp://0.0.0.0:30001`

If you then send a transaction on the node, chainhook will break with `unable to find block XYZ` where XYZ is the transactionID

If you don't have -zmqpubhashtx=tcp://0.0.0.0:30001 it works just fine as long as you've enabled zeromq on the chainhook binary.

The fix for this is subscribing only to the `hashblock` event                       

components/chainhook-event-observer/src/observer/mod.rs 
line 436
`socket.subscribe("hashblock").await?;`

**Comment by lgalabru** [comment]
Thanks for opening this issue @a-straus. Issue will be fixed on https://github.com/hirosystems/chainhook/pull/258 merges.
