### ISSUE TITLE
ordinals sat indexing is incorrect for some inscriptions

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/chainhook#259]
Inscription is returned at [satoshi 1196326693122991 in our API and Explorer](https://ordinals.hiro.so/inscription/81703918195a7ff0cb9a0869aac24b2dbe82ffcf5cad523822bc72c81b5c8943i0), while [ordinals.com shows it at satoshi 2708111118072](https://ordinals.com/inscription/81703918195a7ff0cb9a0869aac24b2dbe82ffcf5cad523822bc72c81b5c8943i0)

**Comment by rafaelcr** [comment]
@lgalabru another example:
https://ordinals.com/inscription/3d57068b5c035a4de98d59ba0ca36aca9ac480f1e23ff501e16fb4aca6bcf6a2i0
https://ordinals.hiro.so/inscription/3d57068b5c035a4de98d59ba0ca36aca9ac480f1e23ff501e16fb4aca6bcf6a2i0

**Comment by lgalabru** [comment]
Thanks for opening this issue @rafaelcr. Issue identified and fixed, we have a new container starting step 2 hopefully tomorrow, I'll make sure it runs with that fix.

**Comment by rafaelcr** [comment]
Thanks @lgalabru !

**Comment by lgalabru** [comment]
Addressed with latest.
