### ISSUE TITLE
Outdated docker image

### ISSUE THREAD

**Issue by utibeabasi6** [hirosystems/chainhook#263]
Hey
I would like to run the chainhook node as part of my kubernetes cluster. 
Firstly, is this recommended?
And secondly, it looks like the docker image [here](https://hub.docker.com/r/hirosystems/chainhook-node) is outdated. Last update 3 months ago

**Comment by utibeabasi6** [comment]
@lgalabru ?

**Comment by lgalabru** [comment]
Our CI is unfortunately broken at the moment. Meanwhile, you should be able to rely on this images that I'm manually pushing to my personal repo https://hub.docker.com/repository/docker/ludovic/chainhook-node.
Or if you're a Github action ninja, I'd take your help 😂
