### ISSUE TITLE
Does chainhook have support for dogecoin?

### ISSUE THREAD

**Issue by cmyk47** [hirosystems/chainhook#267]
I don't think it's the right channel to talk about this, but I haven't found any other.

The Dogecoin network (originally based on Litecoin, which in turn was originally based on Bitcoin) is growing a lot, and even more so in recent weeks with the ordinals (called doginals/drc-20), and at the infrastructure/tools level it is very immature (for Dogecoin in general not only for Ordinals).

I was wondering if this indexer is or will be compatible with Dogecoin.

If it's compatible, or maybe with a few small changes it can be, I think you have a great market to grow. And what about ordinals-explorer? is supported? and ordinals-api is supported?

Maybe I can help but I don't know where to start.

Thanks 👍

**Comment by smcclellan** [comment]
@cmyk47 It does not currently support DOGE as we're focused on STX and BTC. We welcome contributions in the future.
