### ISSUE TITLE
docker image build error

### ISSUE THREAD

**Issue by pupudaye** [hirosystems/chainhook#270]
build list:
chainhook-event-observer.dockerfile
chainhook-node.dockerfile

I'm trying to compile them, but I get the error
#18 0.307 cp: cannot stat 'target/release/chainhook-event-observer': No such file or directory

Secondly, I don't understand the relationship between the two. I hope to build ordinals-api on the upper layer based on chainhook. I don't understand which one is the service I should use.

**Comment by lgalabru** [comment]
Addressed in latest version of `main`. `chainhook-event-observer.dockerfile` was an artifact from the past.
