### ISSUE TITLE
Getting-started steps can be improved

### ISSUE THREAD

**Issue by sabbyanandan** [hirosystems/chainhook#273]
While using `0.13.0`, I encountered the following, so documenting my observations here.

1: Creating a "testnet" config still defaults to "mainnet" as the mode in the generated file.

```
╰─$ chainhook config new --testnet
Created file Chainhook.toml
```

Result:
```
[storage]
driver = "redis"
redis_uri = "redis://localhost:6379/"
cache_path = "cache"

[chainhooks]
max_stacks_registrations = 500
max_bitcoin_registrations = 500

[network]
mode = "mainnet"
bitcoind_rpc_url = "http://localhost:8332"
bitcoind_rpc_username = "devnet"
bitcoind_rpc_password = "devnet"
stacks_node_rpc_url = "http://localhost:20443"

[[event_source]]
tsv_file_url = "https://archive.hiro.so/mainnet/stacks-blockchain-api/mainnet-stacks-blockchain-api-latest.gz"
```

2: Remove `$` from copyable commands from markdown. Devs would have to explicitly remove `$` for the pasted command to work.

3: **config -> config-path:**

The command has evolved, so the docs and guides needs an update. The below statement is also missing an extra `-` before `config-path`.

> Developers can customize their Bitcoin node's credentials and network address by adding the flag -config=/path/to/config.toml.

```
╰─$ chainhook predicates scan ./hello-ordinals.json --testnet --config=./btcconfig.toml
\error: Found argument '--config' which wasn't expected, or isn't valid in this context

	Did you mean '--config-path'?
```

4: Given `--devnet` is not an option, can we error on `chainhook config new --devnet`?

5: Given no "devnet", why are we defaulting the generated config with devnet/devnet as the user/pass for the node/GUI access? That could be confusing to end users. 

```
[network]
mode = "mainnet"
bitcoind_rpc_url = "http://localhost:8332"
bitcoind_rpc_username = "devnet"
bitcoind_rpc_password = "devnet"
stacks_node_rpc_url = "http://localhost:20443"
```

6: The command `chainhook predicates scan ./path/to/predicate.json --testnet` will only work if the bitcoind node is accessible at the RPC location at http://localhost:8332, which wasn't clear to me from the error message. Perhaps move the customizing command above and explicitly mention that the default URL points to http://localhost:8332 upfront, so users can customize it before running the command. 

```
╰─$ chainhook predicates scan ./hello-ordinals.json --testnet
unable to retrieve Bitcoin chain tip (JSON-RPC error: transport error: Couldn't connect to host: Connection refused (os error 61))
```
Alternatively, we could improve the above error message with the actual RPC URL Chainhooks tried accessing. The boilerplate message with additional details can be helpful to end users.

**Comment by sabbyanandan** [comment]
cc: @LakshmiLavanyaKasturi

**Comment by sabbyanandan** [comment]
A few other Docs-specific observations below.

1: The bitcoin and stacks examples start with easy steps to generate a simpler "hello world" variant of predicates. However, it immediately jumps to `if-then` and `then-that` options, which is confusing. As a reader of the docs, I treat them as continuing docs from the "hello world" example, but it is not continuity. They are separate. In the [GitHub README](https://github.com/hirosystems/chainhook#development-workflow-for-bitcoin-chainhooks), however, there is a horizontal line with a title that separates these sections. In docs, however, they are presented continuously, which is confusing--screenshot below.

<img width="1071" alt="image" src="https://github.com/hirosystems/chainhook/assets/1562654/782d9ceb-b485-46ca-97fd-22fd8bd693a7">

2: Because of the previous confusion, the last portion of that docs (ie: "Putting all the above configurations together") is making me want to copy+paste the YAML config into the generated file, and I am furthermore confused, given they are 2 distinct examples.

3: This section in the docs may have formatting issues. Someone can copy the YAML config as-is, but the in between description requires commenting, perhaps?

<img width="885" alt="image" src="https://github.com/hirosystems/chainhook/assets/1562654/cf88edc0-f69f-4107-bcd1-70ed7ad40a25">

**Comment by lgalabru** [comment]
@sabbyanandan can we close this issue?

**Comment by sabbyanandan** [comment]
Given all the recent improvements, I think we can close it. @LakshmiLavanyaKasturi: Do you have any open items?

**Comment by LakshmiLavanyaKasturi** [comment]
Removing '$' from the commands is the one missing. PR created for it: https://github.com/hirosystems/chainhook/pull/351.

**Comment by LakshmiLavanyaKasturi** [comment]
Fixes https://github.com/hirosystems/chainhook/pull/351
