### ISSUE TITLE
chainhook start error

### ISSUE THREAD

**Issue by pupudaye** [hirosystems/chainhook#279]
control_port = 20446
ingestion_port = 20445

The chainhook did not listen to the port after it was started, what is the problem?

**Comment by lgalabru** [comment]
Could you please provide more context? Thanks!

**Comment by lgalabru** [comment]
Feel free to re-open when you get back to this, but make sure you're installing and using the latest version :)

**Comment by pupudaye** [comment]
I use the relevant information below to start the chain hook only to see the structure, but not to start port monitoring.
If I want to use ordinals-api, chainhook doesn't have listening port, I can't configure ordinals-api env.ts correctly


chainhook service start --predicate-path=./ordinals.json  --config-path=./config.toml

[storage]
driver = "memory"
redis_uri = ""
cache_path = "./data2"

[chainhooks]
max_stacks_registrations = 500
max_bitcoin_registrations = 500

[network]
mode = "mainnet"
bitcoind_rpc_url = ""
bitcoind_rpc_username = ""
bitcoind_rpc_password = ""
stacks_node_rpc_url = "https://stacks-node-api.mainnet.stacks.co/"




{
  "chain": "bitcoin",
  "uuid": "818725a4-555d-46db-a60c-213a506b37ba",
  "name": "inscription_feed",
  "version": 1,
  "networks": {
    "mainnet": {
      "start_block": 767430,
      "end_block": 793083,
      "if_this": {
        "scope": "ordinals_protocol",
        "operation": "inscription_feed"
      },
      "then_that": {
        "file_append": {
          "path": "ordinals.txt"
        }
      }
    }
  }
}
