### ISSUE TITLE
Unable to parse the first inscription

### ISSUE THREAD

**Issue by beyondblog** [hirosystems/chainhook#281]
Hey, I found that this judgment seems to be wrong, causing the inscription of the first block to be skipped

```rust
     if raw_block.height as u64 > ordinal_computing_height 
     // maybe it should be
     if raw_block.height as u64 >= ordinal_computing_height 
```

https://github.com/hirosystems/chainhook/blob/c83a272b170c5c791da699ea05907cf7ab316444/components/chainhook-sdk/src/hord/db/mod.rs#LL731C38-L731C38

**Comment by lgalabru** [comment]
Hi @beyondblog! I think you're correct. In the past I was using a older block than the block height of inscription 0, but recently updated this. Will fix, thanks!
