### ISSUE TITLE
Augment /ping endpoint with health related metrics

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/chainhook#285]
Schema prototype:

```json
{
  "chain_tips": {
      "stacks": <BlockIdentifier>,
      "bitcoin": <BlockIdentifier>,
  },
  "running_predicates": <integer>,
  "last_block_ingestion_at": <DateTime>
}
```

**Comment by lgalabru** [comment]
+ measure delta between last block ingested and chaintip of the underlying stacks node (by fetching on a regular basis /v2/info)

**Comment by MicaiahReid** [comment]
Other potential fields:
 - last reorgs for stacks/bitcoin
 - for each predicate, when was the positive evaluation
 - consider splitting status by chain to make data readability better
 - maybe split `running_predicates` into `active_predicates`/`expired_predicates`
