### ISSUE TITLE
Chainhooks Productionized: Specify CI/CD pipelines to be built via Github actions

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/chainhook#288]
To be specified.

**Comment by smcclellan** [comment]
This may be completed by DevOps; task here is to specify our needs, coordinate w/DevOps to have it built.

**Comment by smcclellan** [comment]
Blocked by https://github.com/hirosystems/clarinet/issues/1078 as it will use a similar approach.

**Comment by smcclellan** [comment]
Tracked: https://github.com/hirosystems/ordhook/pull/132

**Comment by smcclellan** [comment]
Next step: Copy/paste CI from ordhook to chainhook.

**Comment by smcclellan** [comment]
@MicaiahReid looking into an issue with the solution.

**Comment by MicaiahReid** [comment]
Done! CI is working now working after creating a `.releaserc` and creating a `main` branch
