### ISSUE TITLE
`chainhook service start --predicate-path` doesn't trigger http_post hook 

### ISSUE THREAD

**Issue by 0xtrou** [hirosystems/chainhook#292]
The chainhook service doesn't trigger the http_post hook or do I have to run scan manually ?

**Comment by smcclellan** [comment]
@0xTraderTrou The docs are forthcoming and will help with this ticket.

**Comment by 0xTraderTrou** [comment]
thank you, looking forward to it

**Comment by 0xTraderTrou** [comment]
hey how is it going?

**Comment by LakshmiLavanyaKasturi** [comment]
The docs are updated https://docs.hiro.so/chainhook/how-to-guides/how-to-run-chainhook-as-a-service-using-bitcoind#initiate-chainhook-service. @0xtrou Please reopen if you find issues.
