### ISSUE TITLE
make the `contract_identifier` arg be optional in `print_event` predicate

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/chainhook#294]
The `print_event` predicate currently requires the `contract_identifier` argument:

```json5
// Get any transaction emitting given print events predicate
// `contract-identifier` mandatory argument admits:
//  - string type, fully qualifying the contract to observe. example: `ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.monkey-sip09`
// `contains` mandatory argument admits:
//  - string type, used for matching event
{
    "if_this": {
        "scope": "print_event",
        "contract_identifier": "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.monkey-sip09",
        "contains": "vault"
    },
}
```

However, in order for the Token Metadata API to detect SIP-019 notifications and SFT mint events, we must be able to inspect *all* print events from *all* contracts to see if they conform to the required structure.

Could we make the `contract_identifier` arg be optional so we can monitor all print events on the stacks chain with this predicate if it isn't specified?

**Comment by smcclellan** [comment]
@rafaelcr I understand this ticket is blocking the Urgent-priority https://github.com/hirosystems/token-metadata-api/issues/146. If that's the case, this one is also Urgent priority. Do you agree with this prioritization?

**Comment by sabbyanandan** [comment]
@smcclellan: Let's bump this up to "Urgent", given it is a gnarly blocker for Metadata API.

**Comment by rafaelcr** [comment]
Yes, agreed @smcclellan

**Comment by MicaiahReid** [comment]
@rafaelcr @sabbyanandan We've upgraded the priority and I'm working on it!

**Comment by rafaelcr** [comment]
Thanks @MicaiahReid !
