### ISSUE TITLE
keep predicate registration api open when startup predicates are passed

### ISSUE THREAD

**Issue by MicaiahReid** [hirosystems/chainhook#298]
Currently, if `chainhook service start` is used with the `--predicate-path` argument, we don't start the predicate registration API, even if it's enabled in the config:
https://github.com/hirosystems/chainhook/blob/69e122112740e5e8c9f3f468c49b1fe905f22f69/components/chainhook-cli/src/cli/mod.rs#L440

We should probably start the API regardless of if predicates are passed on startup.

**Comment by sabbyanandan** [comment]
Agreed on starting the API regardless of the predicates.
