### ISSUE TITLE
Fix and improve chainhook client types

### ISSUE THREAD

**Issue by BLuEScioN** [hirosystems/chainhook#314]
Fix incorrect types
- [ ] p2pkh
- [ ] p2sh
- [ ] p2wpkh
- [ ] p2wsh
- [ ] leader_registered instead of leader_key_registered

Break types up to make them more consumable
- [ ] Break up predicates into BitcoinIfThis and StacksIfThis
- [ ] BitcoinScopes and StacksScopes
- [ ] IfThat type
- [ ] AdditionalConfig and BitcoinAdditionalConfig and StacksAdditionalConfig

If you look at chainhook-types and chainhook-config [here](https://github.com/hirosystems/artemis/pull/550/files#diff-a3a259fcc39dbdcc9945fa3baea720dc597dcaae5a0a7990de2a061912917794), you can get a good idea of how I am consuming my own chainhook types on the client side

**Comment by rafaelcr** [comment]
@BLuEScioN I think some of the types you mention are already broken up, like here: https://github.com/hirosystems/chainhook/blob/develop/components/client/typescript/src/schemas/stacks/if_this.ts

Are you able to import them? Each of those has its own exported type
