### ISSUE TITLE
Add CI tests for chainhooks to check that all predicates work on both mainnet and testnet

### ISSUE THREAD

**Issue by BLuEScioN** [hirosystems/chainhook#317]

**Comment by lgalabru** [comment]
Addressed in https://github.com/hirosystems/chainhook/pull/344

**Comment by MicaiahReid** [comment]
@lgalabru @BLuEScioN  I interpreted "predicates work" to mean the registered predicates are triggered appropriately on mainnet and testnet. My PR (#344) tests against any breaking changes in the predicate API schema - essentially any possible fields for `network`, `if_this`, `then_that`, and the filters are all tested to be valid for the API. If we change any of those fields, the tests will fail. However, these tests don't verify that a registered predicate actually does anything.

Does my PR address the intent of this issue, or do we need to keep open until the actual predicate being triggered is tested?

**Comment by BLuEScioN** [comment]
> keep open until the actual predicate being trigger

I think this works. It means I can confidently register chainhooks/predicates knowing they have been validated on the API side. Knowing whether the predicates are firing is important but I'm sure that can be handled elsewhere in other tests or vai alerts
