### ISSUE TITLE
Hard to identify chainhooks

### ISSUE THREAD

**Issue by BLuEScioN** [hirosystems/chainhook#322]

**Comment by BLuEScioN** [comment]
Something went wrong on the backend has no further information and the wording should be betterx`

**Comment by smcclellan** [comment]
@BLuEScioN This isn't showing on any boards now. Do you need anything here?

**Comment by lgalabru** [comment]
Addressed with https://github.com/hirosystems/chainhook/pull/344 and https://github.com/hirosystems/chainhook/pull/326
