### ISSUE TITLE
Add last triggered timestamp to GET and LIST endpoints

### ISSUE THREAD

**Issue by BLuEScioN** [hirosystems/chainhook#324]
Aug 21st, 2023:
After discussing this requirement with @MicaiahReid and @BLuEScioN, we will add `last_triggered` (i.e., timestamp) as part of the GET and LIST endpoints.
Sabby will open a separate issue to account for the error messages.

Was 2nd:

>Add these fields to the `GET` and `LIST` endpoint:
1: Last Updated: Timestamp
2: Last Triggered: Timestamp
>Add this to `GET` endpoint:
1: 1-line of the last log: String (maybe 100 chars?)

Was 1st: 
> Currently its only possible to tell whether a chainhook is still active by determining whether the endblock specified in the chainhook config has been surpassed or not, or whether the startblock has been reached yet. But there is a third bit of information that may determine whether or not the chainhook is still active - the number of occurences before expiration. Currently, there is no way to retrieve how many times the chainhook has been activated. Thus, there is no way to accurately determine if the chainhook is still active. I recommend that an isActive prop be added to the GET and/or LIST endpoints to make it easier to consume this information. This kind of information would be very useful to display for chainhooks on the Platform.

**Comment by sabbyanandan** [comment]
@lgalabru: Additionally, it'd be great to include the following in the response payload for _each_ chainhook (if it is not expensive).

+ Last run's timestamp
+ Last run's 1-line log or any details about it

**Comment by sabbyanandan** [comment]
@lgalabru: It'd be great to get the "liveness" visibility of the each hook. How about:

1: Is Active: Boolean
2: Last updated: Timestamp
3: 1-line of the last log: String (maybe 100 chars?)

**Comment by smcclellan** [comment]
The ability to query this info is already live on `GET /v1/chainhooks/:uuid`.

This issue will track verifying the freshness of the data being returned AND have the data returned at the `LIST` endpoint.

**Comment by smcclellan** [comment]
@andresgalante Targeting by August 28th (next Iteration). Does that work for your timing?

**Comment by sabbyanandan** [comment]
@smcclellan: I would prioritize this as urgent.

**Comment by sabbyanandan** [comment]
> The ability to query this info is already live on `GET /v1/chainhooks/:uuid`.

Also, @smcclellan, we may have to add additional bits what I listed in [my comment](https://github.com/hirosystems/chainhook/issues/324#issuecomment-1677597568), correct? I don't think they are in the response.

**Comment by MicaiahReid** [comment]
Hey @BLuEScioN, I'm starting work on this, and I've got some questions.
>Last Updated: Timestamp
What do you mean by "updated" here? My understanding is that you can't update a predicate, only delete and create.

>1-line of the last log
What logs are you referring to here? We don't keep previous logs on-hand, and storing them would be a pretty large change. Maybe we can get on a call so we can come up with ideas on how to get the info you are needing.

**Comment by sabbyanandan** [comment]
I updated the description based on the discussion and what we decided. I also created https://github.com/hirosystems/chainhook/issues/396 to track this as a separate enhancement. 

@smcclellan: Let's scope 396, and we can discuss the priorities then.
