### ISSUE TITLE
Allow regex for `contains` based chainhooks

### ISSUE THREAD

**Issue by aulneau** [hirosystems/chainhook#348]
When creating a chainhook that listens for a print_event, it'd be great to be able to use regex to define the condition for `contains`. 

Example: I'd like to create a print_event predicate that only listens for `stack-extend` or `stack-increase` but exclude `stack-aggregation-*`

**Comment by LakshmiLavanyaKasturi** [comment]
This is a WIP feature. @Ludo and @MicaiahReid, Please assign it back to me once the feature is developed and is ready for doc updates.

**Comment by MicaiahReid** [comment]
Hey @LakshmiLavanyaKasturi, this feature is ready to document now! I've added a test that demonstrates the new `if_this` condition [here](https://github.com/hirosystems/chainhook/blob/131809e7d2b8e4b48b83114440a4876ec9aee9ee/components/chainhook-cli/src/service/tests/mod.rs#L311C1-L311C1). Let me know if you have any questions!

**Comment by LakshmiLavanyaKasturi** [comment]
https://github.com/hirosystems/chainhook/pull/394

**Comment by MicaiahReid** [comment]
Completed by #394 and #380
