### ISSUE TITLE
NFT-event file append pulls back events that are not associated with the asset-identifier  

### ISSUE THREAD

**Issue by timstackblock** [hirosystems/chainhook#354]
**Describe the bug**
NFT-event file append pulls back events that are not associated with the asset-identifier   asset_identifier": "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.redeeem-nft-v0",

I ran this predicate and only wanted to return mint events for "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.redeeem-nft-v0"

Here is the predicate file 

<img width="873" alt="Screen Shot 2023-07-26 at 10 50 52 AM" src="https://github.com/hirosystems/chainhook/assets/49165468/c19d179e-715c-4c96-a4ba-69957b93af2f">

I successfully got records for that asset identifier which is great but the file is very large and there are a lot of records for other NFTs that do not mat ch the asset identifier "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.redeeem-nft-v0",

Here are screen shots this is the GOOD data

<img width="994" alt="Screen Shot 2023-07-26 at 10 52 39 AM" src="https://github.com/hirosystems/chainhook/assets/49165468/c4ffa4cd-ba19-473c-b4b7-aa94a33a228f">

Here is the bad data the event type also seems to not filter for "MINT:" events and is pulling in data that is outside of the scope. You will see transfer data and you will see asset identifiers for "asset_class_identifier":"ST39HFKW38EPPPRQ1R52GK02WCN8314DQAP1P6AYE.test-wn::wolfs-pack-academy" the filtering seems to be broken.

<img width="980" alt="Screen Shot 2023-07-26 at 10 55 39 AM" src="https://github.com/hirosystems/chainhook/assets/49165468/65b0c99d-31df-4610-a0e8-690636ec8f8f">

Please let me know if you need more information

**Comment by lgalabru** [comment]
Thanks for the time spent on this @timstackblock, I think it's time for us to take on https://github.com/hirosystems/chainhook/issues/287.
@timstackblock in future bug reports, could you please provide the predicate in json format, instead of screenshots?
Also when reporting the results, providing a copy paste (full block or full transaction) would speed up debugging!
Thank you again for your halp 🙏

**Comment by timstackblock** [comment]
> Thanks for the time spent on this @timstackblock, I think it's time for us to take on #287. @timstackblock in future bug reports, could you please provide the predicate in json format, instead of screenshots? Also when reporting the results, providing a copy paste (full block or full transaction) would speed up debugging! Thank you again for your halp 🙏

sure no problem @lgalabru will do

**Comment by timstackblock** [comment]
sure let me take a look

**Comment by timstackblock** [comment]
ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.redeeem-nft-v0"

https://explorer.hiro.so/txid/0xf3fd7d7278a104ddafaf4517d371bdbf3d75b8ecdbb4cc4ac51488f4240f76de?chain=testnet

Chainhooks seems like it cant pull back the MINT events for the NFT that are present in the explorer. I am also getting the error message when running the predicate. Please let me know if there is some wrong with the asset I am selecting.

<img width="565" alt="Screen Shot 2023-08-03 at 12 19 52 PM" src="https://github.com/hirosystems/chainhook/assets/49165468/24948b7d-385f-4f5f-9942-4cbc59dba3e3">



I have copied and pasted the predicate here so you can run it.

`{`
`  "chain": "stacks",`
`  "uuid": "c3c3bf08-2035-40bf-a5eb-0e4295911f8a",`
`  "name": "nft event file",`
`  "version": 1,`
`  "networks": {`
`    "testnet": {`
`      "start_block": 60150,`
`      "end_block": 60153,`
`      "if_this": {`
`        "scope": "nft_event",`
`        "asset_identifier": "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.punker-nft3",`
`        "actions": ["claim"]`
`      },`
`      "then_that": {`
`        "file_append": {`
`          "path": "tests/stacks-predicates/nft-event/nft-event-file-result.json"`
`        }`
`      }`
`    }`
`  }`
`}`

**Comment by timstackblock** [comment]
Please scroll to the bottom of this page to see the MINT events chainhooks should be pulling back

https://explorer.hiro.so/txid/ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.redeeem-nft-v0?chain=testnet

Here is the error I am getting when I run the predicate

<img width="565" alt="Screen Shot 2023-08-03 at 12 19 52 PM" src="https://github.com/hirosystems/chainhook/assets/49165468/7656a106-ed5c-4b07-934d-c3113bbe31b2">

Chainhooks seems like it cannot pull back the mint events for the NFT it is getting 0 occurrences but the NFT events are present. There is also a strange new error `Aug 03 16:19:25.089 ERRO unable to parse stacks block_header EOF while parsing a string at line 1 column 3616` Please let me know if there is an issue with the NFT I have selected

I have pasted the predicate below so you can run it

`{`
`  "chain": "stacks",`
`  "uuid": "c3c3bf08-2035-40bf-a5eb-0e4295911f8a",`
`  "name": "nft event file",`
`  "version": 1,`
`  "networks": {`
`    "testnet": {`
`      "start_block": 20835,`
`      "end_block": 38357,`
`      "if_this": {`
`        "scope": "nft_event",`
`        "asset_identifier": "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.redeeem-nft-v0",`
`        "actions": ["mint"]`
`      },`
`      "then_that": {`
`        "file_append": {`
`          "path": "automate/tests/stacks-predicates/nft-event/nft-event-file-result.json"`
`        }`
`      }`
`    }`
`  }`
`}`

**Comment by timstackblock** [comment]
The first MINT NFT_EVENT is in block 20835 that is why we start the block there and the last one is in 38357 there are many in between

https://explorer.hiro.so/txid/0xf3fd7d7278a104ddafaf4517d371bdbf3d75b8ecdbb4cc4ac51488f4240f76de?chain=testnet

<img width="979" alt="Screen Shot 2023-08-04 at 8 55 47 AM" src="https://github.com/hirosystems/chainhook/assets/49165468/36c70e48-6668-4666-bef3-0286cd52c682">

**Comment by MicaiahReid** [comment]
Hey @timstackblock, I've found what's going on here. The asset id you are using is `deployer_address.contract_name`, but it should be `deployer_address.contract_name::nft_name`. For example, rather than `"asset_identifier": "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.redeeem-nft-v0"`, it should be `"asset_identifier": "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.redeeem-nft-v0::redeeem-nft-v0"`

**Comment by MicaiahReid** [comment]
This predicate worked for me:
```JSON
{
  "chain": "stacks",
  "uuid": "c3c3bf08-2035-40bf-a5eb-0e4295911f8a",
  "name": "nft event file",
  "version": 1,
  "networks": {
    "testnet": {
      "start_block": 20835,
      "end_block": 20835,
      "if_this": {
        "scope": "nft_event",
        "asset_identifier": "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.redeeem-nft-v0::redeeem-nft-v0",
        "actions": ["mint"]
      },
      "then_that": {
        "file_append": {
          "path": "automate/tests/stacks-predicates/nft-event/nft-event-file-result.json"
        }
      }
    }
  }
}

```

**Comment by timstackblock** [comment]
Thanks for looking into this. One last question using this updated asset identifier I got 22 occurrences but there are 53 mint function calls in the explorer between 20835 and 38357

<img width="1089" alt="Screen Shot 2023-08-07 at 10 57 17 AM" src="https://github.com/hirosystems/chainhook/assets/49165468/e3ed2c81-6497-437f-a4b5-3c03add49bda">


<img width="226" alt="Screen Shot 2023-08-07 at 11 04 32 AM" src="https://github.com/hirosystems/chainhook/assets/49165468/0dbdae2e-73e1-4f43-9d20-155cf22c15ff">

**Comment by timstackblock** [comment]
Got it makes sense I was expecting to count events but the block for the event is being pulled back
