### ISSUE TITLE
FT-event file append pulls back events that are not associated with the asset-identifier 

### ISSUE THREAD

**Issue by timstackblock** [hirosystems/chainhook#358]
**Describe the bug**
FT-event file append pulls back events that are not associated with the asset-identifier asset_identifier": "ST113MYNN52BC76GWP8P9PYFEP7XWJP6S5YFQM4ZE.shitty-coin::shitty",

I ran this predicate and only wanted to return ft-events for "ST113MYNN52BC76GWP8P9PYFEP7XWJP6S5YFQM4ZE.shitty-coin::shitty"

Here is the predicate file
<img width="994" alt="Screen Shot 2023-07-28 at 1 40 15 PM" src="https://github.com/hirosystems/chainhook/assets/49165468/b110daa4-743e-41c8-a305-cce3ba542f6f">

I successfully returned records for that asset identifier which is great but the file is very large and there are a lot of records for other FTs that do not match the asset identifier "ST113MYNN52BC76GWP8P9PYFEP7XWJP6S5YFQM4ZE.shitty-coin::shitty"

Here are screen shots this is the GOOD data

<img width="1036" alt="Screen Shot 2023-07-28 at 1 43 38 PM" src="https://github.com/hirosystems/chainhook/assets/49165468/1e54bbea-7b68-4d9a-8e2a-948f1518d403">

Here is the bad data the which is not "ST113MYNN52BC76GWP8P9PYFEP7XWJP6S5YFQM4ZE.shitty-coin::shitty" and is  outside of the scope. You will see FT data with asset identifiers for "asset_class_identifier":"ST2QYV0FDQE9FA10Q4W66P9Z03R1DDCDSKJFK095D.miamicoin-token::miamicoin" the filtering seems to be broken.

<img width="1038" alt="Screen Shot 2023-07-28 at 1 43 50 PM" src="https://github.com/hirosystems/chainhook/assets/49165468/77ef776e-0621-434b-815f-b53ca0c1ac3f">

**Comment by lgalabru** [comment]
Thanks for the time spent on this @timstackblock, I think it's time for us to take on https://github.com/hirosystems/chainhook/issues/287.

**Comment by MicaiahReid** [comment]
@timstackblock This issue should be fixed currently in the `develop` branch. Can you confirm?

**Comment by lgalabru** [comment]
Addressed with latest

**Comment by timstackblock** [comment]
sure let me take a look

**Comment by timstackblock** [comment]
I ran the predicate 2 times and I am getting an error 

<img width="563" alt="Screen Shot 2023-08-03 at 11 54 32 AM" src="https://github.com/hirosystems/chainhook/assets/49165468/2a1eaefb-0461-47cf-9584-13fbdbe0009e">


I have pasted in the predicate so you can run it as well and see if you are getting that same error and no data back.

`{`
`  "chain": "stacks",`
`  "uuid": "a2b55836-5fbe-441b-9de8-c24c3cda286c",`
`"name": "FT Event File",`
`  "version": 1,`
`  "networks": {`
`    "testnet": {`
`      "start_block": 26000,`
`      "end_block": 26050,`
`      "expire_after_occurrence": 1,`
`      "if_this": {`
`        "scope": "ft_event",`
`        "asset_identifier": "ST113MYNN52BC76GWP8P9PYFEP7XWJP6S5YFQM4ZE.shitty-coin::shitty",`
`        "actions": ["transfer"]`
`      },`
`      "then_that": {`
`        "file_append": {`
`          "path": "automate/tests/stacks-predicates/ft-event/ft-event-file-result.json"`
`        }`
`      }`
`    }`
`  }`
`}`

**Comment by timstackblock** [comment]
https://explorer.hiro.so/txid/0xb2a8445f65bf09f12f2d448ab74fa2c95dae4856ec13fe94c5f401040fed30e1?chain=testnet

Block 26043 has a transfer

<img width="939" alt="Screen Shot 2023-08-04 at 8 52 15 AM" src="https://github.com/hirosystems/chainhook/assets/49165468/d4a7b348-1aaf-4ef0-966a-5aee61aff190">

**Comment by MicaiahReid** [comment]
It looks like the name of the event your filtering is off. You have the asset id ending in `::shitty` when it should be `::shitty-coin`. Here is a working predicate:
```JSON
{
  "chain": "stacks",
  "uuid": "a2b55836-5fbe-441b-9de8-c24c3cda286c",
  "name": "FT Event File",
  "version": 1,
  "networks": {
    "testnet": {
      "start_block": 26043,
      "end_block": 26043,
      "expire_after_occurrence": 1,
      "if_this": {
        "scope": "ft_event",
        "asset_identifier": "ST113MYNN52BC76GWP8P9PYFEP7XWJP6S5YFQM4ZE.shitty-coin::shitty-coin",
        "actions": ["transfer"]
      },
      "then_that": {
        "file_append": {
          "path": "automate/tests/stacks-predicates/ft-event/ft-event-file-result.json"
        }
      }
    }
  }
}

```

**Comment by timstackblock** [comment]
Thanks for that I updated the predicate and still get 0 occurrences is it working for you?

<img width="1431" alt="Screen Shot 2023-08-07 at 10 50 14 AM" src="https://github.com/hirosystems/chainhook/assets/49165468/df3c4a32-f1c9-436f-9eb9-6fc63e8d4013">
