### ISSUE TITLE
bitcoin predicate "Get any transaction matching a given txid" 0 actions triggered when TXID exist in block

### ISSUE THREAD

**Issue by timstackblock** [hirosystems/chainhook#367]
**Describe the bug**
When running the predicate below I am looking for a transaction that is present in block 80122 chainhooks scans 11 blocks but cannot find the transaction.

```
{
  "uuid": "1",
  "name": "Hello Ordinals",
  "chain": "bitcoin",
  "version": 1,
  "networks": {
    "mainnet": {
      "start_block": 801220,
      "end_block": 801230,
      "if_this": {
        "scope": "txid",
        "equals": "55c86631e9b08b817e6ebac00b9818d1fd49e0a7d6c00429b6e364d3ef845920"
      },
      "then_that": {
        "file_append": {
          "path": "automate/tests/bitcoin-predicates/transaction/transaction-file-result.json",
        }
      }
    }
  }
}
```

Here is a link to the bitcoin transaction it is present ib block 801221 which is in the given range    "start_block": 801220, "end_block": 801230,

https://mempool.space/tx/55c86631e9b08b817e6ebac00b9818d1fd49e0a7d6c00429b6e364d3ef845920

Here is a screenshot of the output

<img width="666" alt="Screenshot 2023-08-08 at 11 53 05 AM" src="https://github.com/hirosystems/chainhook/assets/49165468/46dba3e4-0bca-48fd-a3c5-2ac49ae8af6b">

It is scanning the blocks on my bitcoin server without issue but it doesn't see the transaction and hasn't triggered a file append. Please let me know your thoughts.

**Comment by MicaiahReid** [comment]
Hey @timstackblock, per the docs:
>```
> // Get any transaction matching a given txid
> // `txid` mandatory argument admits:
> //  - 32 bytes hex encoded type. example: 
> {
>    "if_this": {
>        "scope": "txid",
>        "equals": "0xfaaac1833dc4883e7ec28f61e35b41f896c395f8d288b1a177155de2abd6052f"
>    }
>}
>```

I think for the hex encoded id, it needs to be prefixed with `0x`. Can you try that and let me know?

**Comment by timstackblock** [comment]
Thanks for the quick response trying now

**Comment by timstackblock** [comment]
Same result with the `0x`
How does it work for you?
```
{
  "uuid": "1",
  "name": "Hello Ordinals",
  "chain": "bitcoin",
  "version": 1,
  "networks": {
    "mainnet": {
      "start_block": 801220,
      "end_block": 801230,
      "if_this": {
        "scope": "txid",
        "equals": "0x55c86631e9b08b817e6ebac00b9818d1fd49e0a7d6c00429b6e364d3ef845920"
      },
      "then_that": {
        "file_append": {
          "path": "automate/tests/bitcoin-predicates/transaction/transaction-file-result.json"
        }
      }
    }
  }
}
```

**Comment by MicaiahReid** [comment]
Doing some research, I think I've found the source of the bug.

When standardizing a bitcoin block, we require that every transaction input has a `prevout` field, even though it's optional. This means that if the first transaction in a block has an input with no `prevout`, we don't check any transaction in the rest of the block. I need to verify with @lgalabru, but I think this is a pretty major bug.

https://github.com/hirosystems/chainhook/blob/0fbfc763774061e6fe97c00b07e1633217592280/components/chainhook-sdk/src/indexer/bitcoin/mod.rs#L461

**Comment by timstackblock** [comment]
@MicaiahReid after restarted the bitcoind yesterday and re-synced this now works.

<img width="1311" alt="Screenshot 2023-08-11 at 8 12 27 AM" src="https://github.com/hirosystems/chainhook/assets/49165468/a00d3359-cf0b-4c69-a210-2fe166eabf31">


`{"apply":[{"block_identifier":{"hash":"0x00000000000000000002210b020a96cc3933866500b9e5b81da28ffa8d04c87c","index":801221},"metadata":{"network":"mainnet"},"parent_block_identifier":{"hash":"0x000000000000000000040bd26a1922e003f2fd9eed06228f1302c22eafbb52aa","index":801220},"timestamp":1690902231,"transactions":[{"metadata":{"proof":null},"operations":[],"transaction_identifier":{"hash":"0x55c86631e9b08b817e6ebac00b9818d1fd49e0a7d6c00429b6e364d3ef845920"}}]}],"chainhook":{"is_streaming_blocks":false,"predicate":{"equals":"0x55c86631e9b08b817e6ebac00b9818d1fd49e0a7d6c00429b6e364d3ef845920","scope":"txid"},"uuid":"1"},"rollback":[]}`

**Comment by MicaiahReid** [comment]
Looks like everything is good here. There's a more specific issue that's related, which we have documented on #381. Closing this issue.
