### ISSUE TITLE
Missing Inscriptions / Discrepancy between chainhook and hord

### ISSUE THREAD

**Issue by ryanwaits** [hirosystems/chainhook#374]
**Describe the bug**
When running both `chainhook` and `hord` services with the same configuration, there seems to be a discrepancy in the number of triggers being emitted. (`chainhook` does not pick up any while `hord` picks up 2)

I was running through the [how-to-run-chainhook-as-a-service-using-bitcoind](https://github.com/hirosystems/chainhook/blob/develop/docs/how-to-guides/how-to-run-chainhook-as-a-service-using-bitcoind.md#prerequisites) and noticed that there might be missing inscriptions when running `chainhook` when compared to scanning blocks using `hord` for streaming activity.

Here is the `ordinals.json` file
```json
{
  "uuid": "1",
  "name": "Hello Ordinals",
  "chain": "bitcoin",
  "version": 1,
  "networks": {
      "mainnet": {
          "start_block": 767430,
          "end_block": 767753,
          "if_this": {
              "scope": "ordinals_protocol",
              "operation": "inscription_feed"
          },
          "then_that": {
              "file_append": {
                  "path": "inscription_feed.txt"
              }
          }
      }

  }
}
```

Here is a screenshot of the results for running it with `chainhook`
<img width="520" alt="Screenshot 2023-08-09 at 9 08 24 AM" src="https://github.com/hirosystems/chainhook/assets/3207017/56cebc61-2007-444f-8cd8-8acab4d8b82c">

Here is the result when scanning same blocks with `hord`, you'll notice it triggered 2 actions
<img width="917" alt="Screenshot 2023-08-09 at 9 08 38 AM" src="https://github.com/hirosystems/chainhook/assets/3207017/26b04ab1-ee39-4840-bfe9-fd700ac0105a">

In this particular configuration, since both services are using the same `bitcoind` configuration - we should expect the same 2 triggers to occur when running both `chainhook` and `hord`.

**Comment by timstackblock** [comment]
I am getting the same thing with chainhooks

**Comment by lgalabru** [comment]
The ordinals predicates are technically still available in the chainhook repo, but the ordinals indexing logic was moved to ordhook.

**Comment by ryanwaits** [comment]
got it - thanks! ill assume going forward that predicate will be removed from chainhook, and anything ordinals related will be handled by ordhook

**Comment by smcclellan** [comment]
We will track fixing the documentation drift in this ticket @LakshmiLavanyaKasturi.

**Comment by LakshmiLavanyaKasturi** [comment]
@lgalabru, Are we ready to remove Ordinals protocol documentation from the Chainhook docs?

**Comment by LakshmiLavanyaKasturi** [comment]
I prefer to remove these after the Ordhook documentation is live. @lgalabru WDYT?
