### ISSUE TITLE
can't match any ordinals when using chainhook predicates scan

### ISSUE THREAD

**Issue by Hodgewhj** [hirosystems/chainhook#409]
when starting chainhook to scan btc ordinals,  there seems to be  not match any data.

here is predicate json file:

```
{
  "uuid": "1",
  "name": "Hello Ordinals",
  "chain": "bitcoin",
  "version": 1,
  "networks": {
      "mainnet": {
          "start_block": 777534,
          "end_block": 777540,
          "if_this": {
              "scope": "ordinals_protocol",
              "operation": "inscription_feed"
          },
          "then_that": {
              "file_append": {
                  "path": "ordinals.txt"
              }
          }
      }

  }
}
```
start command is :
```
chainhook predicates scan hello-ordinals.json  --config-path ./Chainhook.toml
```

<img width="559" alt="image" src="https://github.com/hirosystems/chainhook/assets/41406643/1b310923-8877-4c7c-a2e0-42141fe204f7">

I also try another range below
startblock 767430 end block 767753

<img width="573" alt="image" src="https://github.com/hirosystems/chainhook/assets/41406643/507753c0-2b5f-4129-a24d-e7acc59ab713">

<img width="533" alt="image" src="https://github.com/hirosystems/chainhook/assets/41406643/f74c07a6-9714-486c-90ba-abfa5e3cf536">

**Comment by qustavo** [comment]
Which bitcoind version are you using? I believe you are on v22.x or below?

**Comment by Hodgewhj** [comment]
> Which bitcoind version are you using? I believe you are on v22.x or below?
yes, i check the bitcoind version and found is v22.0.0. which version should i use? thanks a lot !

![image](https://github.com/hirosystems/chainhook/assets/41406643/c92179df-b7c5-4ea4-b1ef-a90b6cb91d60)

**Comment by qustavo** [comment]
try to update to v23+. This might be relates to https://github.com/hirosystems/chainhook/issues/405

**Comment by Hodgewhj** [comment]
> try to update to v23+. This might be related to #405

i got it, thanks a lot for your reply. i will try it and see if works

**Comment by Hodgewhj** [comment]
> try to update to v23+. This might be related to #405
i updated the bitcoind version to v25.0.0 and try again, the result is  blew, there seems not to change

<img width="1712" alt="image" src="https://github.com/hirosystems/chainhook/assets/41406643/f1754896-df97-46b0-b017-fce8e7d53c53">

**Comment by Hodgewhj** [comment]
> bitcoin-cli getnetworkinfo
yes, i run the command, and the network seem to  be normal ,  i also telnet port 8332 and 18543 which metioned in the doc:

<img width="613" alt="image" src="https://github.com/hirosystems/chainhook/assets/41406643/4cbbf955-fc45-4af3-9128-68d897bf7e63">


<img width="556" alt="image" src="https://github.com/hirosystems/chainhook/assets/41406643/87545d8a-aa81-4f9f-b8c4-5f5476d5ed41">

**Comment by qustavo** [comment]
version still returns `22` (see version and subversion). Did you restart the deamon after upgrading?

**Comment by Hodgewhj** [comment]
> version still returns `22` (see version and subversion). Did you restart the deamon after upgrading?
yes, you are right, i update the version but forget to restart.  but still exists some problems

when the range :  startblock 767430 end block 767753
<img width="833" alt="image" src="https://github.com/hirosystems/chainhook/assets/41406643/0e5ed5dc-17c3-4c5a-a859-8800db3d23f4">

when the range: startblock:807430, end block：860000
seems can't fetch and parse block
<img width="888" alt="image" src="https://github.com/hirosystems/chainhook/assets/41406643/62ada743-4ffc-419d-bd35-a07475deb537">

**Comment by Hodgewhj** [comment]
> version still returns `22` (see version and subversion). Did you restart the deamon after upgrading?

guess maybe i configure wrong somewhere, do you need other configurations or node status?

**Comment by Hodgewhj** [comment]
> version still returns `22` (see version and subversion). Did you restart the deamon after upgrading?

i seem to  know the reason why range 807430 to 860000 occur error,  cause the btc node sync height is 806309.  

i readjust the range , the problem now is that,  still can't any ordinals data

<img width="611" alt="image" src="https://github.com/hirosystems/chainhook/assets/41406643/c928a9e8-6b7e-4ddf-98e0-014f05293307">

**Comment by qustavo** [comment]
@Hodgewhj from what I see, you upgraded your bitcoind software, but you are still running the old version, hence the `/Satoshi:22.0.0` subversion.
The problem you are having is due to a missing field returned by the bitcoind rpc api. That field has been added on newer versions, and this is why you should upgrade.
Try restarting your bitcoin node with the upgraded software and check if that does the job.

**Comment by Hodgewhj** [comment]
> bitcoin-cli getnetworkinfo
yeah, i know what you mean, the first time you said , i have restart the node, and the version is 25.0

<img width="476" alt="image" src="https://github.com/hirosystems/chainhook/assets/41406643/7f062885-1245-4b56-bc94-4eb57dcacadf">

**Comment by qustavo** [comment]
cool, and  that fixed the initial error retrieving prevout?

**Comment by Hodgewhj** [comment]
> cool, and that fixed the initial error retrieving prevout?

yeah，the error is fixed ！！！

**Comment by Hodgewhj** [comment]
> cool, and that fixed the initial error retrieving prevout?

now，it throw no error and san no things ，😭

**Comment by Hodgewhj** [comment]
> @Hodgewhj: Thanks for opening the issue. And @qustavo, appreciate your support in the community.
> 
> As for,
> 
> > now，it throw no error and scan no things ，😭
> 
> @Hodgewhj: Likely, the criteria you're trying to scan for the event aren't reconciling correctly, or no matching events exist in the network. Could you share your latest predicate JSON?

thanks for your reply, the predicate json is below, i copy it for the chain hook test module, i only change the append file path

{
  "uuid": "1",
  "name": "Hello Ordinals",
  "chain": "bitcoin",
  "version": 1,
  "networks": {
      "mainnet": {
          "start_block": 777534,
          "end_block": 777540,
          "if_this": {
              "scope": "ordinals_protocol",
              "operation": "inscription_feed"
          },
          "then_that": {
              "file_append": {
                  "path": "ordinals.txt"
              }
          }
      }

  }
}


<img width="581" alt="image" src="https://github.com/hirosystems/chainhook/assets/41406643/5eba7e37-7f8a-4282-afc5-3133a2de096f">

**Comment by Hodgewhj** [comment]
> @Hodgewhj: Thanks for opening the issue. And @qustavo, appreciate your support in the community.
> 
> As for,
> 
> > now，it throw no error and scan no things ，😭
> 
> @Hodgewhj: Likely, the criteria you're trying to scan for the event aren't reconciling correctly, or no matching events exist in the network. Could you share your latest predicate JSON?

i guess if the condition related to bitcoind configuration,  such as zeromq， i don't know exactly the function of the point,  i just configure it, and now it can be telnet


<img width="587" alt="image" src="https://github.com/hirosystems/chainhook/assets/41406643/efa30896-0f35-4818-bc59-c5e733a02d76">

**Comment by lgalabru** [comment]
hey @Hodgewhj, when working with ordinals, you should be using [ordhook](http://github.com/hirosystems/ordhook) instead.
Feel free to re-open an issue in the repo mentioned above if you're facing some issues.
