### ISSUE TITLE
Not find ordinal protocol parse process in chainhook original code

### ISSUE THREAD

**Issue by Hodgewhj** [hirosystems/chainhook#410]
in order to find why my predicate json can't match any valid data (links : #409) , i scan the chainhook original code and can't seem to find the process of ordinal protocol parsing. (i not familiar with the rust language, so need some help)

one point:
i find the ordinal-Inscription data struct, but i don't find where the struct was created and set value.
<img width="764" alt="image" src="https://github.com/hirosystems/chainhook/assets/41406643/1cd9b3f5-26af-443f-8b77-8e96b2d4edd3">

two point:
here the ordinal_operations was set to empty vec, so according to my understanding, it will not to match any thing in the subsequent process.

<img width="782" alt="image" src="https://github.com/hirosystems/chainhook/assets/41406643/a140066c-185c-402c-92aa-38079984f7c7">
<img width="775" alt="image" src="https://github.com/hirosystems/chainhook/assets/41406643/f97c8b70-24ab-48ac-abc3-a2fca02413d9">

<img width="901" alt="image" src="https://github.com/hirosystems/chainhook/assets/41406643/1fad704d-d72a-428a-9312-bdba6e4002b1">

<img width="1014" alt="image" src="https://github.com/hirosystems/chainhook/assets/41406643/93cbe12c-a2d2-4efa-acbc-9fcbfd312f8b">

<img width="878" alt="image" src="https://github.com/hirosystems/chainhook/assets/41406643/045e88e1-e088-42af-8730-0ade9aec9196">

**Comment by lgalabru** [comment]
hey @Hodgewhj, when working with ordinals, you should be using [ordhook](http://github.com/hirosystems/ordhook) instead.
Feel free to re-open an issue in the repo mentioned above if you're facing some issues.

**Comment by Hodgewhj** [comment]
> Feel free to re-open an issue in the repo mentioned above if you're facing some issues.

thanks for your reply!  i have aleardy found the inscription code in ordhook, but when i use the subcommand "chainhook service start",   it occur blew errors

https://github.com/hirosystems/ordhook/issues/172

![image](https://github.com/hirosystems/chainhook/assets/41406643/6661cec9-5bb1-42b5-a365-35e0ac1f6af3)

**Comment by lgalabru** [comment]
Closing, in favor or https://github.com/hirosystems/ordhook/issues/172
