### ISSUE TITLE
Chainhook is not forwarding the auth header to webhook url for stacks predicates

### ISSUE THREAD

**Issue by BLuEScioN** [hirosystems/chainhook#438]
@micaiah There is a customer who is saying their auth header is not being added to the requests to their webhook url
Here is what platform is sending to chainhook api
```
{
    "name": "For localhost",
    "chain": "stacks",
    "version": 1,
    "networks": {
        "testnet": {
            "if_this": {
                "scope": "contract_call",
                "method": "create-gig",
                "contract_identifier": "ST2GW18TVQR75W1VT53HYGBRGKFRV5BFYNAYRBHF4.Cerulean-marketplace-v1"
            },
            "end_block": null,
            "then_that": {
                "http_post": {
                    "url": "https://update-zero.vercel.app/api/chainhook/updateGig",
                    "authorization_header": "abcdefg"
                }
            },
            "start_block": 107542,
            "decode_clarity_values": true,
            "expire_after_occurrence": null
        }
    }
}
```
Here is the customer's predicate json, which I uploaded using the file upload feature
```
{
  "name": "For localhost",
  "chain": "stacks",
  "version": 1,
  "networks": {
    "testnet": {
      "if_this": {
        "scope": "contract_call",
        "method": "create-gig",
        "contract_identifier": "ST2GW18TVQR75W1VT53HYGBRGKFRV5BFYNAYRBHF4.Cerulean-marketplace-v1"
      },
      "end_block": null,
      "then_that": {
        "http_post": {
          "url": "https://update-zero.vercel.app/api/chainhook/updateGig",
          "authorization_header": "abcdefg"
        }
      },
      "start_block": 107542,
      "decode_clarity_values": true,
      "expire_after_occurrence": null
    }
  }
}
```
It seems like platform is sending the data correctly. Can you check this from your side please?
Here is the link to the thread in Discord - https://discord.com/channels/621759717756370964/1086336958546071666/1161310372700110879
cc @sabby

**Comment by MicaiahReid** [comment]
It looks like we only forward the [`authorization_header`](https://github.com/hirosystems/chainhook/blob/947b11ee989b92fcaab8a4d1d39e83c62a674bd7/components/chainhook-sdk/src/chainhooks/types.rs#L423) field for [bitcoin hooks](https://github.com/hirosystems/chainhook/blob/d9fe5360bb7d09255e3b27e5d71ef61c6d6e87d2/components/chainhook-sdk/src/chainhooks/bitcoin/mod.rs#L260) and not for stacks.
