### ISSUE TITLE
Chainhook status isn't updating past "new"

### ISSUE THREAD

**Issue by BLuEScioN** [hirosystems/chainhook#455]
I noticed on platform stg that several chainhooks were not updating their chainhook status. The chainhook API kept returning status "new" for them, which is a poor UX for users who expect to be able to see the chainhook working in real time.

**Comment by smcclellan** [comment]
@BLuEScioN Is this one still an issue?

**Comment by MicaiahReid** [comment]
I think #509 is the actual underlying cause for this issue. We can close this issue in favor of that one.
