### ISSUE TITLE
implement more useful alerts on chainhook node health

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/chainhook#466]
Now that the ping endpoint is reporting the bitcoin / stacks block heights, the alarming should be revisited, taking this into account.

**Comment by lgalabru** [comment]
![Screenshot 2023-12-22 at 16 44 37](https://github.com/hirosystems/chainhook/assets/87777/8dc5d3c8-16aa-4624-9aa9-ade06e9790b6)

**Comment by smcclellan** [comment]
@lgalabru to indicate which alarms are needed on this repo.

**Comment by MicaiahReid** [comment]
Just adding a quick follow up here - I'm taking on this issue. We'll be adding alerts to Grafana that will notify us if Chainhook block ingestion falls behind block production for either the stacks or bitcoin nodes. 

This is requiring us to update Chainhook to emit Prometheus metrics. PR will be incoming soon!

**Comment by MicaiahReid** [comment]
Closing, because everything is complete on the chainhook side with PR #473. The devops side is being tracked by https://github.com/hirosystems/devops/issues/1543
