### ISSUE TITLE
Investigate incident around block 139053

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/chainhook#467]

**Comment by MicaiahReid** [comment]
Hey @lgalabru, what was the incident? Would our method of investigation be via Grafana? Because I believe Grafana only keeps logs for 7 days, so it may be too late :/

**Comment by smcclellan** [comment]
Closing due to above reason. We will investigate if/when it reoccurs.

**Comment by lgalabru** [comment]
We think this issue was fixed with https://github.com/hirosystems/chainhook/pull/553
