### ISSUE TITLE
[devnet] chainhook is triggering twice

### ISSUE THREAD

**Issue by ryanwaits** [hirosystems/chainhook#483]
**Describe the bug**
On the `devnet` network, each registered predicate will trigger twice.

**To Reproduce**
1. Create a new project with `clarinet new my-project`
2. Create a `file_append` predicate for `contract_deployment ` on `devnet`, use `ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM` as deployer
4. Run `clarinet devnet start` and make sure the predicate is registered
5. See duplicate payloads returned

**Expected behavior**
A single payload should be triggered when a predicate condition is met.

**Screenshots**
<img width="528" alt="Screenshot_2024-01-31_at_5 31 14_PM" src="https://github.com/hirosystems/chainhook/assets/3207017/51db1de5-befe-4045-8053-194e255ca5e1">

**Comment by MicaiahReid** [comment]
@ryanwaits Are you also seeing duplicate data added to your file append results?

**Comment by ryanwaits** [comment]
yes, we've been seeing the data duplicated in both the `file_append` and the `http_post` configurations

**Comment by ryanwaits** [comment]
this is no longer an issue
