### ISSUE TITLE
Classify & format panic logs correctly

### ISSUE THREAD

**Issue by CharlieC3** [hirosystems/chainhook#521]
It seems panic logs are not being printed in correct JSON syntax, which may cause issues when our log collectors try to parse them. Additionally, panic logs may not be getting classified correctly as `fatal` level (a rank above `error` level). [See here for various supported log levels we can use.](https://grafana.com/docs/grafana/latest/explore/logs-integration/#log-level)

```
{thread 'Chainhook event observer' panicked at 'Unable to register new chainhook spec: Network unknown', "components/chainhook-sdk/src/observer/mod.rs:msg1337"::25"
```

Ideally all panics would be printed in valid JSON, and be classified as `fatal` (or something similar to the `critical` log level referenced in the link above).

[Referenced panic](https://github.com/hirosystems/chainhook/blob/384f94ac1e6f216e7016bcd18e36dcb6d5d46f41/components/chainhook-sdk/src/observer/mod.rs#L1337), but a fix may be needed for all panics.

**Comment by aravindgee** [comment]
[Fixing this issue will also unblock [chainhook alerting for thread panic](https://github.com/hirosystems/devops/issues/1647).]
