### ISSUE TITLE
Publish `chainhook` on homebrew, winget, and snapcraft 

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/chainhook#546]
Let's level up the first impression, by simplifying how chainhook can get installed on a computer!
Can we update the CI of this project, to automate version updates on brew and winget? 
Clarinet can be use as an implementation reference.

- [x] homebrew
- [x] winget
- [x] snapcraft

**Comment by MicaiahReid** [comment]
Related: #530

**Comment by MicaiahReid** [comment]
Chainhook is now available to download on homebrew, winget, and snapcraft!
