### ISSUE TITLE
Should there be a bitcoin logo here?

### ISSUE THREAD

**Issue by ECBSJ** [hirosystems/chainhook#576]
On a chainhook watching the Bitcoin mainnet, should there be a Bitcoin logo instead of a Stacks logo?
<img width="478" alt="image" src="https://github.com/hirosystems/chainhook/assets/61910547/0a69a1f4-ff37-4364-b041-0da537021d81">

**Comment by MicaiahReid** [comment]
Yes, definitely. I made [this issue](https://github.com/hirosystems/platform/issues/848) on the Platform side a while back to address this. Chainhook doesn't do anything for that UI, so we'll track this over on the platform side.
