### ISSUE TITLE
Unable to evaluate predicate on Stacks chainstate: unable to retrieve block 157949

### ISSUE THREAD

**Issue by Rapha-btc** [hirosystems/chainhook#625]
**Describe the bug**
Error message: Unable to evaluate predicate on Stacks chainstate: unable to retrieve block 157949

Transaction ID 
Address 
Block#  157949
Time stamp

**To Reproduce**
Check print screen of the chain hook params.
<img width="1045" alt="Screenshot 2024-07-17 at 12 49 44 PM" src="https://github.com/user-attachments/assets/f4da95a5-062d-4193-b227-6a76a21199e3">

Params inside the screen but not visible:
<img width="424" alt="Screenshot 2024-07-17 at 4 09 07 PM" src="https://github.com/user-attachments/assets/dcd934d7-a4be-4aa8-ad89-1c2bed16e4b8">

SPP3HM2E4JXGT26G1QRWQ2YTR5WT040S5NKXZYFC.stx-ft-swap
https://backend-neon-ecru.vercel.app/api/chainhook/create-swap

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/67294073-0b39-470d-a48d-b1aa10878b7b)

**Comment by Rapha-btc** [comment]
Same issue with this one:

SPP3HM2E4JXGT26G1QRWQ2YTR5WT040S5NKXZYFC.sub100neon-invader
https://backend-neon-ecru.vercel.app/api/chainhook/neon-sub100inv
<img width="1045" alt="Screenshot 2024-07-17 at 12 49 44 PM" src="https://github.com/user-attachments/assets/4bb3966c-daa9-4863-b146-3e7f74be3e6b">

**Comment by rafaelcr** [comment]
I think this could also be related to the TSV errors we've seen in other places @csgui , we should take a look at that mechanism asap

**Comment by Rapha-btc** [comment]
Thanks for the support, fellows. Hopefully this helps improve Chainhook overall. It's shaping up to be a game-changer for Stacks, and Hiro offering it as a service is huge for builders!

**Comment by Rapha-btc** [comment]
Is there anything I can do on my side to test or help with this issue? Thank you.

**Comment by Rapha-btc** [comment]
Issue resolved! Thanks for your support. Not sure if it was fixed on your end or if my database redeployment did the trick, but either way, thanks!
<img width="1391" alt="Screenshot 2024-07-21 at 5 34 52 PM" src="https://github.com/user-attachments/assets/257ad352-4253-4b8c-9e6f-11fd72fe2813">
