### ISSUE TITLE
improve deployed testnet resilience

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/chainhook#647]
The chainhook deployment for primary testnet is having a few issues that have been difficult to debug and solve. This issue will keep track of all the different sub-tasks that need to be resolved before we can get that environment back on track:

* #646 
* #643 
* #630 
* #623 
* #620

**Comment by smcclellan** [comment]
The remainder of this is moved to [this ticket](https://github.com/hirosystems/chainhook/issues/687).
